name: chatwork
version: 0.1.3.4
synopsis: The ChatWork API in Haskell
description: See README at <https://github.com/matsubara0507/chatwork#readme>
maintainer: MATSUBARA Nobutada
author: MATSUBARA Nobutada
copyright: 2017-2018 MATSUBARA Nobutada
license: MIT
github: matsubara0507/chatwork
category: Web

ghc-options: -Wall

dependencies:
  - base >=4.7 && <5
  - aeson >=1.0.2.1 && <1.5
  - aeson-casing >=0.1.0.5 && <0.2
  - bytestring >=0.10.8.1 && <0.11
  - connection >=0.2.7 && <0.3
  - data-default-class >=0.1.2.0 && <0.2
  - http-api-data >=0.3.5 && <0.3.9
  - http-client >=0.5.5.0 && <0.6
  - http-client-tls >=0.3.3.1 && <0.4
  - http-types >=0.9.1 && <0.13
  - req >=1.0.0 && <1.2.0
  - text >=1.2.2.1 && <1.3

library:
  source-dirs: src

executables:
  sample-exe:
    source-dirs: sample
    main: Main.hs
    dependencies:
      - chatwork

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
      - src
    dependencies:
      - servant-server >=0.9.1.1 && <0.15
      - warp >=3.2.11 && <3.3
      - hspec >=2.4.1 && <2.6
